### ISSUE TITLE
Possibility to return the ID of the created entity

### ISSUE THREAD

**Issue by Henrriky** [fschmtt/keycloak-rest-api-client-php#84] opened 2024-01-17 18:23 UTC
I believe that returning information about the created entity is very useful for several use cases

**Comment by fschmtt** [comment] 2024-01-20 12:48
Hey, it's by design that _commands_ and _queries_ are separated in this library; _commands_ should IMO not return any response.

Also, Keycloak's Admin REST API does not return details of modified resources, which would make it necessary nonetheless to run a _query_ against the server to retrieve the wanted information.

To me it seems sufficient and reasonable to do, e.g.:

```php
$realm = new Realm(
    displayName: 'My Random Realm ' . $random,
    id: 'my-random-realm-' . $random,
    realm: 'my-random-realm-' . $random,
);

$keycloak->realms()->import($realm);

$realm = $keycloak->realms()->get($realm->getName());
```

Thanks for the suggestion, but I'll close this for now. If you have a convincing use case for your request, feel free to reopen 🙂

**Closed by fschmtt** 2024-01-20 12:48 UTC
